/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dar.Gui.Sales;

import dar.Gui.GuiIcon;
import dar.dbObjects.Production.ProductListView;
import dar.localDB.LocalWraper;
import dar.localDB.ProductViewHandler;
import java.awt.Color;
import java.sql.Date;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.NumberFormatter;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author ldulka
 */
public class newSale extends javax.swing.JFrame {
    
    private static final double GST = 10;
    private final Date date;
    private final LocalWraper db;
    private final ProductViewHandler ph;
    private ArrayList<ProductListView> prodList;
    private ArrayList<ProductListView> prodOnSite;
    private static boolean writeDown = false;
    public static boolean running;
    private NumberFormat format;
    private NumberFormatter formatter;
    private final SalesGui g;
    /**
     * Creates new form newSale
     */
    public newSale(LocalWraper db, Date date,SalesGui g) {
        this.db = db;
        this.date = date;
        this.g = g;
        //this.ph = null;
        createCurrencyFormater();
        
        initComponents();        
        System.out.println(db.userData.getLoginName());
        ph = new ProductViewHandler(db, db.userData, date);
        refreshLists();
        AutoCompleteDecorator.decorate(productList);        
        GuiIcon icon = new GuiIcon(this,"Create");
        this.running = true;
    }

    private void refreshLists() {
        prodList = ph.createProductList(date);
        prodOnSite = ph.getProductsOnSiteList();
        
        ph.fillComboBoxWithProducts(productList);        
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        productList = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        direction = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        incGST = new javax.swing.JTextField();
        extGST = new javax.swing.JTextField();
        amount = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sales");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Product Details"));

        jLabel1.setText("Product:");

        productList.setModel(new DefaultComboBoxModel());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(productList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(productList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Sales Info"));

        jLabel2.setText("Direction:");

        direction.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IN", "OUT" }));

        jLabel3.setText("Tonnage");

        jLabel4.setText("t");

        jLabel5.setText("Price inc GST:");

        jLabel6.setText("Price exc GST:");

        incGST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incGSTActionPerformed(evt);
            }
        });
        incGST.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                incGSTKeyReleased(evt);
            }
        });

        extGST.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                extGSTKeyReleased(evt);
            }
        });

        amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                amountKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(direction, 0, 117, Short.MAX_VALUE)
                    .addComponent(incGST))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(amount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addComponent(extGST, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(direction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(incGST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(extGST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Create16.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Exit16.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        closeWindow();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(writeDown){
            insertIntoDB();
        } else {
            JOptionPane.showMessageDialog(null,"Price is not numeric number", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        running = false;
    }//GEN-LAST:event_formWindowClosing

    private void incGSTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_incGSTKeyReleased
        applyChanges(incGST, extGST, 0);
    }//GEN-LAST:event_incGSTKeyReleased

    private void extGSTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_extGSTKeyReleased
        applyChanges(extGST, incGST, 1);
    }//GEN-LAST:event_extGSTKeyReleased

    private void amountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountKeyReleased
        checkNumber(amount);
    }//GEN-LAST:event_amountKeyReleased

    private void incGSTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incGSTActionPerformed
        if(writeDown){
            insertIntoDB();
        } else {
            JOptionPane.showMessageDialog(null,"Price is not numeric number", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_incGSTActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amount;
    private javax.swing.JComboBox<String> direction;
    private javax.swing.JTextField extGST;
    private javax.swing.JTextField incGST;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> productList;
    // End of variables declaration//GEN-END:variables

    private void closeWindow() {
        running = false;
        this.dispose();        
    }

    private void createCurrencyFormater() {
        format = NumberFormat.getCurrencyInstance(Locale.US);
        //format.setMaximumFractionDigits(2);

        formatter = new NumberFormatter(format);
        //formatter.setAllowsInvalid(true);
        //formatter.setOverwriteMode(true);        
        //formatter.setCommitsOnValidEdit(true);
    }

    private void applyChanges(JTextField textField1, JTextField textfield2, int operation) {
        double num = checkNumber(textField1);
        if(num>=0){             
            switch(operation){
                case 0:
                    textfield2.setText(String.format("%.2f",(num/(GST/100+1D))));
                    break;
                case 1:
                    textfield2.setText(String.format("%.2f",(num*(GST/100+1D))));
                    break;
            }

        } else {
            if(!textField1.getText().isEmpty())
                textField1.setText("0");
        }                            
    }

    private void insertIntoDB() {
        //allocate variables
        ProductListView selectedProduct = (ProductListView) productList.getSelectedItem();
        int productID = selectedProduct.getProductID();
        String direction = (String) this.direction.getSelectedItem();        
        double amount = checkNumber(this.amount);
        double incGST = checkNumber(this.incGST);
        double extGST = checkNumber(this.extGST);        
        if(amount>=0 && incGST>=0 && extGST>=0){
            System.out.println("inserting sales into db");
            db.dbInsert("Sales", new Object[][]{{"SiteID","ProductID","Direction","Amount","PriceIncGST","PriceExGST","DateFor"},
                {db.userData.getSiteID(),productID,direction,amount,incGST,extGST,date}});
            g.refreshData(date);
            closeWindow();
        } else {
            JOptionPane.showMessageDialog(null,"Not all fields are filled properly","Error",JOptionPane.ERROR_MESSAGE);
        }
    }

    private double checkNumber(JTextField tfield) {
        double number = -1;
        try {
            number = Double.parseDouble(tfield.getText());
            writeDown = true;            
            tfield.setForeground(Color.black);
        } catch (Exception e) {
            writeDown = false;
            tfield.setForeground(Color.red);
        }
        return number;
    }
}
