/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dar.Gui.Production;

import dar.Functions.FileLogger;
import dar.Functions.Functions;
import dar.Gui.Gui;
import dar.Gui.GuiIcon;
import dar.localDB.ProductViewHandler;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author ldulka
 */
public class moreRecipes extends javax.swing.JFrame {

    private ArrayList<recipeDetail> rcplist;
    private GridBagConstraints c = new GridBagConstraints();;
    private final ProductViewHandler pw;
    private final double amount;
    private final String notes;
    private final int AllocationId;
    private final int TrType;
    private final Date date;
    private final AddProduct p;
    private final Gui g;


    public moreRecipes(ArrayList<recipeDetail> rs, ProductViewHandler pw, double amount, String notes, int AllocationID, Date date, int TrType,AddProduct p, Gui g) {        
        this.pw = pw;
        this.rcplist = rs;
        this.amount = amount;
        this.notes = notes;
        this.AllocationId = AllocationID;
        this.date = date;
        this.TrType = TrType;
        this.g = g;
        this.p = p;
        initComponents();
        Functions.setFrameMinimumSize(this);
        editComponents();
        GuiIcon icon = new GuiIcon(this,"Application");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        components = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select recipe");
        setMinimumSize(getSize());

        javax.swing.GroupLayout componentsLayout = new javax.swing.GroupLayout(components);
        components.setLayout(componentsLayout);
        componentsLayout.setHorizontalGroup(
            componentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 197, Short.MAX_VALUE)
        );
        componentsLayout.setVerticalGroup(
            componentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 111, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(components);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/Create16.png"))); // NOI18N
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean write = false;
        int recipeID=0;
        String recipeName = "";
        for (recipeDetail detail : rcplist) {
            if(detail.myRadio.isSelected()){
                write = true;
                recipeID = detail.recipeID;
                recipeName = detail.recipeName;
            }
        }
        if(write){
            ResultSet rr = pw.getIngredientsByRecipeID(recipeID);
            String msg = String.format("Recipe %s found\nAdding to used in production:\n", recipeName);
            try {
                while(rr.next()){
                    msg += String.format("%s: %s\n", rr.getString("ProductName"),rr.getDouble("Used")*amount);
                    //decide wheter product is already utilised or not if yes update if not add
                    pw.insertProduction(rr.getInt("PRODUCTALLOCATIONID"), rr.getDouble("Used")*amount, notes, date, 4);
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
                new FileLogger(ex.toString());
            }
            pw.insertProduction(AllocationId,amount,notes,date,TrType);
            p.dispose();
            this.dispose();
            g.refreshLists();
            JOptionPane.showMessageDialog(null,msg,"Success",JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null,"No recipe selected","error",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel components;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void editComponents() {
        components.setLayout(new GridBagLayout());
        c.weightx = 1;
        c.gridx = 0;
        c.gridy = 0;
        c.anchor = GridBagConstraints.NORTHWEST;
        System.out.println(rcplist.size());
        ButtonGroup bG = new ButtonGroup();
        for (recipeDetail recipes : rcplist) {
            bG.add(recipes.myRadio);
            components.add(recipes,c);  
            c.gridy++;                 
        }
        components.revalidate();
        components.repaint();         
    }
}
