/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dar.Gui.AplicationLog;

import dar.Functions.FileLogger;
import dar.Gui.GuiIcon;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author ldulka
 */
public class ALGui extends javax.swing.JFrame {

    /**
     * Creates new form ALGui
     */
    public ALGui() {
        initComponents();
        GuiIcon icon = new GuiIcon(this);
        displayChangelog();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        appLog = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        appLog.setColumns(20);
        appLog.setRows(5);
        jScrollPane1.setViewportView(appLog);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    private void displayChangelog() {         
        File f = new File("./log/"+createFileName());
        if(f.exists()){
            try {
                BufferedReader changelogR = new BufferedReader(new FileReader(f));
                String x;
                while((x = changelogR.readLine())!=null){
                    appLog.append(x+"\n");
                }
            } catch (FileNotFoundException ex) {
                ex.printStackTrace();
            } catch (IOException ex) {
                new FileLogger(ex.getStackTrace());
            }
        } else {
            appLog.setVisible(false);
        }
    }
    
    private String createFileName() {
        SimpleDateFormat dt = new SimpleDateFormat("yyyy-MM-dd");
        String date = dt.format(new Date());
        return date+"_Systemlog.txt";
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea appLog;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
